### ISSUE TITLE
Test name not populated into context when using cucumber 

### ISSUE THREAD

**Issue by nikolaypisanchev** [zinserjan/wdio-visual-regression-service#42]
I'm using the cucumber framework and for me in the getScreenshotName() function the testName is undefined. 
From first look it seems that cucumber uses it's own set of hooks (described at the bottom of http://webdriver.io/guide/testrunner/configurationfile.html) and the context.test is set from currentTest, initialized in a beforeTest hook, which seems to not be executed in the cucumber case.

**Comment by zinserjan** [comment]
Never used cucumber before but as far as I found out, that title should be available:
https://github.com/webdriverio/wdio-cucumber-framework/blob/5e7276e58b8e8ad8f46f782ee7b94784c1de6cec/lib/reporter.js#L68

which looks similiar to:
https://github.com/webdriverio/wdio-mocha-framework/blob/4cfafffded6391ee1e476f43ba39ea1a19186a35/lib/adapter.js#L217-L235
https://github.com/webdriverio/wdio-mocha-framework/blob/4cfafffded6391ee1e476f43ba39ea1a19186a35/lib/adapter.js#L169


Can you research what you get as parameter in the following method?
https://github.com/zinserjan/wdio-visual-regression-service/blob/ad0ca9c14b8e3a2ab0f764d56eee364a15fc4eae/src/VisualRegressionLauncher.js#L57

and tweak the following to your needs:
https://github.com/zinserjan/wdio-visual-regression-service/blob/ad0ca9c14b8e3a2ab0f764d56eee364a15fc4eae/src/VisualRegressionLauncher.js#L93

Alternatively try to add the right hooks, store the information you need and make them accessible :)

**Comment by rgustavsson** [comment]
@nikolaypisanchev 
Did you manage to do some tweaking?

**Comment by freddyfallon** [comment]
I have the same issue, how do I get the parameter in the method you describe?

**Comment by Emmet-McGuire** [comment]
I am also having this problem.  What's the correct way to get the test name when you are using Cucumber?

**Comment by lbergman** [comment]
It is a bit tricky to say what should be a test name with cucumber any way. Steps are identified by a step definition that typically is a sentence with params/regex. Feature doesn't really have a name, but a "As a....I want...So that" description. And scenarios doesn't have a name either, and can have several runs where only example values differ.

In my case what I really want is the name I have given to the feature file. From that I can see that is not actually exposed in any other way than the full path to the file. So I added this to my wdio config to get a value I can use in my getScreenshotName function:

```
beforeFeature: function (feature) {
    const match = feature.uri.match(/[\\\/]([a-z]+)\./);
    testName = match[1];
},
```

**Comment by rohityadavrv** [comment]
@nikolaypisanchev : were you able to run the visual regression test through cucumber framework?
